name: GraalVM Native Image builds
on: 
  push:
    branches:
      - main
      - develop
jobs:
  build:
    name: reveal-microservice on ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1.0.9
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Build the microservice
        run: |
          ./mvnw -q -B native:compile -Pnative -DskipTests -DskipNativeTests
      
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: reveal-microservice-${{ matrix.os }}
          path: |
              target/reveal-microservice
              target/reveal-microservice.exe

        
